### PR TITLE
Add Vulkan to cmake build

### PR DESCRIPTION
**Pull request by abetlen**
- Adds a `GGML_VULKAN` option to cmake to allow building those sources into ggml
- Adds the `ggml_vk_generate_shaders.py` and `ggml-vulkan-shaders.hpp` from `llama.cpp` to `src/`

### CODE REVIEW

**Comment by ggerganov** [comment]
We should wait for https://github.com/ggerganov/llama.cpp/issues/5356 to see if they come up with a way to re-organize the Vulkan shaders

**Comment by abetlen** [comment]
Makes sense, no rush for me I was just experimenting with the new backends.

**Comment by foldl** [comment]
https://github.com/ggerganov/llama.cpp/issues/5356 is closed for being inactive.

So, any updates?

**Comment by abetlen** [comment]
@ggerganov maybe for now I can just remove the auto-generated `.hpp` file and update the sync scripts. That should at least allow users to build with Vulkan by first running the python script to generate the shaders. How does that sound?

**Comment by ggerganov** [comment]
@abetlen Ok, let's do that

**Comment by abetlen** [comment]
@ggerganov okay, I've removed the auto-generated file and updated the sync scripts. I also updated the `ggml_vk_generate_shaders.py` file to match the current `ggml-vulkan` files.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
