### PR TITLE
feat: adds `ggml_pad_reflect_1d`

### PR DESCRIPTION
**Pull request by balisujohn**
This adds an op that mirrors the behavior or PyTorch's [ReflectionPad1d](https://pytorch.org/docs/stable/generated/torch.nn.ReflectionPad1d.html) operation. 

Implementations for cuda and CPU are provided.

Tests still need to be added, so marking as a draft PR from now. 

The cpu version of the op was derived with permission from @PABannier's implementation discussed here: https://github.com/ggerganov/ggml/issues/819

### CODE REVIEW

**Comment by balisujohn** [comment]
I added a test in `test-backend-ops` and also added `test-pad-reflect-1d.cpp` which I verified works with and without the `#define GGML_USE_CUBLAS`, though I'm not sure if the cuda versions of the ops are currently tested in the CI/CD or how to accomplish that. 

I think this is ready for review.

**Comment by balisujohn** [comment]
A test I wasn't sure how to add was "check if it correctly fails when called with a pad length not shorter than ne0 of the input tensor."

**Comment by balisujohn** [comment]
Or and wrt the `is_2D` argument I support it but I'd ideally like to leave it to a future PR.

**Comment by ggerganov** [comment]
Some similar comments as in the `ggml_conv_transpose_1d` PR

Regarding the `is_2D`: currently the `im2col` is an exception - the only op that uses this pattern. Probably it is better to change `im2col` to not use it, since the alternative pattern with dimensions suffix (i.e. `_1d`, `_2d`, etc.) is well established

**Comment by balisujohn** [comment]
OK ready for review again : ^)

**Comment by PABannier** [comment]
Hello @slaren @ggerganov ! Do you plan to merge this operation? This would be super helpful for [Encodec.cpp](https://github.com/PABannier/encodec.cpp) to support the Metal backend.

**Comment by ggerganov** [comment]
Hey @PABannier, this PR needs to be updated to the latest `ggml` changes before merging.

**Comment by PABannier** [comment]
Hello @balisujohn ! Do you plan to finish this PR soon? Otherwise, I'm happy to finish yours if you give me the permission to push on your fork.

**Pull request closed without merging**
