### PR TITLE
Update replit inference code to match reference

### PR DESCRIPTION
**Pull request by lukasmoellerch**
Fixes the replit example to work with the new version of the model (tested with 1e1a20a5764458844056ca44c25617c91840d8c9 Sun May 28 04:43:38 2023)

### CODE REVIEW

**Comment by lukasmoellerch** [comment]
Model file uploaded here: https://huggingface.co/lukasmoeller/replit-code-v1-3b-ggml, will upload quantised version later

**Comment by lukasmoellerch** [comment]
This actually changes a bit more than that PR; feel free to close though

**Comment by klosax** [comment]
> This actually changes a bit more than that PR; feel free to close though

I will close #206 .

**Comment by darianss** [comment]
I'm getting a SEGFAULT when running this (quantized -f16) on a 950 token input. My setup is an M1 Max 64G. Exact message: 
```
command: ./build/bin/replit -m replit-code-v1-3b/ggml-model-f32.bin -f prompt.txt --top_k 0 --top_p 0.95 --temp 0.2 -n 1500
error message: ggml_new_tensor_impl: not enough space in the context's memory pool (needed 268799024, available 268435456)
```

**Comment by aseok** [comment]
@lukasmoellerch tried commits, but error persists.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
