### PR TITLE
sync : llama.cpp

### PR DESCRIPTION
**Pull request by ggerganov**

### CODE REVIEW

**Comment by 0cc4m** [comment]
I'm not sure what the normal process to sync llama.cpp and ggml is, but it seems Vulkan is broken on both the master and the sync branch (Missing shaders, inconsistent code state). Is there something I can do to help with that?

**Comment by ggerganov** [comment]
Ah, thanks for spotting. Adding a CI workflow that builds with Vulkan would help.

I'll see if I can fix the build before merging this PR

**Comment by ggerganov** [comment]
Should be good now - does it build on your side too @0cc4m?

We can add the CI on `master` later

**Comment by 0cc4m** [comment]
> Should be good now - does it build on your side too @0cc4m?
> 
> We can add the CI on `master` later

It does build now, thank you.

**Comment by zcbenz** [comment]
@ggerganov There are some files like `ggml/include/ggml-amx.h` created in a new `/ggml` root directory, is there a reason that they are put in `/ggml` instead of `/src` like other files?

**Comment by ggerganov** [comment]
Oh, the sync script messed up somehow and I didn't even notice. Thanks for letting me know.

**Pull request merged**
