### PR TITLE
Vocab support for special tokens

### PR DESCRIPTION
**Pull request by mverrilli**
Adding support for special tokens. This is in order to give priority to these tokens during tokenization in cases where the model was trained specifically around using them.

Note: There is probably some limitation around regex.

### CODE REVIEW

**Comment by mverrilli** [comment]
Hi @ggerganov I needed this in order to line up with how Dolly was trained as the special tokens needed priority.  Let me know if there is a better way to accomplish this? I assume other models may run into similar issues. Thanks! https://github.com/mverrilli/ggml/tree/dolly-v2/examples/dolly-v2

**Comment by Green-Sky** [comment]
afaik llama.cpp uses weighted vocab https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L189-L200

**Comment by mikev-db** [comment]
@Green-Sky Ahh, I was working from the common libs which has a regex style tokenizer. This is just so it can support the example better (Dolly special tokens have a space in them), but I think if I were to create a project out of it I'd redo that part. Thanks for pointing that out.

**Comment by mverrilli** [comment]
@Green-Sky Ahh, I was working from the common libs which has a regex style tokenizer. This is just so it can support the example better (Dolly special tokens have a space in them), but I think if I were to create a project out of it I'd redo that part. Thanks for pointing that out.

**Comment by mverrilli** [comment]
Closing this as it is included in #132

**Pull request closed without merging**
