### PR TITLE
alibi implementation by @hhamud

### PR DESCRIPTION
**Pull request by danforbes**
See discussion here https://github.com/rustformers/llama-rs/pull/141#issuecomment-1523900931

CC: @philpax @KerfuffleV2

### CODE REVIEW

**Comment by philpax** [comment]
For some additional clarification: this was originally implemented by @NouamaneTazi in https://github.com/NouamaneTazi/bloomz.cpp to implement the BLOOM model. We've implemented it in `llama-rs`, but we'd like to avoid patching GGML for this one operation.

There may be a way to implement this operation in terms of the existing primitives, as hypothesised by @KerfuffleV2, but we haven't fully investigated this possibility.

**Comment by Green-Sky** [comment]
you can add authors etc to git commits. I think that would be better than the github mentions.

**Comment by danforbes** [comment]
> you can add authors etc to git commits. I think that would be better than the github mentions.

Indeed, however, I do not know their email address.

**Comment by philpax** [comment]
The email address should be present in the commits; I don't think GitHub will show you, but you can see it by viewing the commit in your Git tool of choice.

**Comment by danforbes** [comment]
> The email address should be present in the commits; I don't think GitHub will show you, but you can see it by viewing the commit in your Git tool of choice.

All set ✅

**Review by ggerganov — APPROVED** [review]
Thanks! Great contribution

**Pull request merged**
