### PR TITLE
Conv 2D CPU Implementation

### PR DESCRIPTION
**Pull request by dmille**
- Variable padding (p0 and p1)
- Variable stride (s0 and s1)
- Variable dilation (d0 and d1)
-  f16 kernel, f32 input tensor
- Utilizes ggml_vec_dot_f16 (SIMD optimized)

### CODE REVIEW

**Comment by ggerganov** [comment]
Thanks! Let's resolve the conflicts and merge

**Comment by dmille** [comment]
@ggerganov Conflicts are resolved!

**Comment by ggerganov** [comment]
Thanks! Will first look to merge https://github.com/ggerganov/ggml/pull/325 and then this one

**Comment by dmille** [comment]
I needed strides of variable length for my project so I went ahead and updated the function to support both dilation and strides.

**Pull request merged**
