### PR TITLE
feat: support bloom-1b4-zh

### PR DESCRIPTION
**Pull request by xingchensong**
- model link: https://huggingface.co/Langboat/bloom-1b4-zh  this is a 1.4B model based on [bigscience/bloom-1b7](https://huggingface.co/bigscience/bloom-1b7).
 The vocabulary is pruned from 250880 to 46145 with Chinese corpus to reduce GPU memory usage. So the total parameter is 1.4b now.
- results look good to me

fp16：
image
image

q4_0
image
image

### CODE REVIEW

**Comment by xingchensong** [comment]
PPL test on single sentence:
image

**Comment by ggerganov** [comment]
Thanks for this contribution!

Are you interested in trying to add support for this model straight into `llama.cpp?
Recently, we have started to support many different model architectures and people will help out with testing and keeping up-to-date.

**Comment by xingchensong** [comment]
> Thanks for this contribution!
> 
> Are you interested in trying to add support for this model straight into [llama.cpp](https://github.com/ggerganov/llama.cpp)?
> Recently, we have started to support many different model architectures and people will help out with testing and keeping up-to-date.
> 

sure, will do it ASAP

**Comment by ggerganov** [comment]
Great! Take a look at this PR to get an idea of what is needed:

https://github.com/ggerganov/llama.cpp/pull/3187

**Pull request closed without merging**
