### PR TITLE
mpt : fix `n_ctx`

### PR DESCRIPTION
**Pull request by marella**
Also `max_seq_len` doesn't seem to be used anywhere. Is that expected?

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Hm, I'm confused. It looks like `max_seq_len` corresponds to `n_ctx`.
Looking at HF repo, it seems that it should be 2048, but here we have it defined as `4096`:

https://huggingface.co/mosaicml/mpt-7b/blob/main/config.json#L39

Need to download the model and test it

**Comment by marella** [comment]
Yeah I also think `max_seq_len` should be `n_ctx`.
I also mentioned it to the author who created it in https://github.com/ggerganov/ggml/issues/168#issuecomment-1555877761

**Comment by marella** [comment]
Should I change `max_seq_len` to `n_ctx`? [Replit example](https://github.com/ggerganov/ggml/blob/c2fab8a3503b6e6fbf480be993f24c21951d3af0/examples/replit/main.cpp#L240) is using `max_seq_len` as `n_ctx` everywhere.

**Comment by lukasmoellerch** [comment]
The main reason was that we always allocate max seq length which might require too much ram for kv cache on low-ram machines

**Comment by ggerganov** [comment]
Ah yes, I remember now. Let me think about this some more then.

**Comment by ggerganov** [comment]
> The main reason was that we always allocate max seq length which might require too much ram for kv cache on low-ram machines

Ok, but the way it is implemented now, we allocate with `n_ctx = 4096`:

https://github.com/ggerganov/ggml/blob/c2fab8a3503b6e6fbf480be993f24c21951d3af0/examples/mpt/main.cpp#L21

This is 2x more than `max_seq_len`.
What is reasoning for line 21 ?

**Comment by lukasmoellerch** [comment]
> > The main reason was that we always allocate max seq length which might require too much ram for kv cache on low-ram machines
> 
> Ok, but the way it is implemented now, we allocate with `n_ctx = 4096`:
> 
> https://github.com/ggerganov/ggml/blob/c2fab8a3503b6e6fbf480be993f24c21951d3af0/examples/mpt/main.cpp#L21
> 
> This is 2x more than `max_seq_len`. What is the reasoning for line 21 ?

It was mainly intended as a fix for running the storywriter model which has a much higher seq length

**Comment by marella** [comment]
Should we do something like `n_ctx = min(max_seq_len, 4096)`?

**Comment by klosax** [comment]
I suggest adding a command line parameter for setting n_ctx. Default value could be 512 as in llama. Maximum value could be max_seq_len.

**Comment by ggerganov** [comment]
Yes, we can do both of these suggestions

**Comment by marella** [comment]
Added the `min()` condition.

I can add the command line parameter later in a separate PR. Can it be added to all models not just MPT?

**Comment by lukasmoellerch** [comment]
> I suggest adding a command line parameter for setting n_ctx. Default value could be 512 as in llama. Maximum value could be max_seq_len.

Yes, I like the suggestion, many new models don’t have an inherent max seq length either, thus setting it to that was a bit arbitrary in the first place.

**Pull request closed without merging**
