### PR TITLE
sync : llama.cpp

### PR DESCRIPTION
**Pull request by ggerganov**

### CODE REVIEW

**Comment by slaren** [comment]
The moved files weren't removed, they are duplicated now.

**Comment by slaren** [comment]
You probably need to update the oneAPI etc SYCL libraries. See #10267 for more details.

**Comment by mudler** [comment]
> You probably need to update the oneAPI etc SYCL libraries. See [ggerganov/llama.cpp#10267](https://github.com/ggerganov/llama.cpp/pull/10267) for more details.

Gonna check in a bit. Thank you @slaren!

**Comment by mudler** [comment]
that was it indeed! just for reference if anyone is facing this, had to update the Docker base image from `intel/oneapi-basekit:2024.2.0-devel-ubuntu22.04` to `intel/oneapi-basekit:2025.0.0-0-devel-ubuntu22.04`

**Pull request merged**
