### PR TITLE
sync : llama.cpp

### PR DESCRIPTION
**Pull request by ggerganov**
Testing new script for automatic sync

### CODE REVIEW

**Comment by slaren** [comment]
Very nice, looks like this script will greatly simplify the syncs, while also attributing the changes tot he original authors.

**Comment by ggerganov** [comment]
Yup, looks like `git` is very powerful and has the necessary functionality to automate this process

**Comment by slaren** [comment]
This should sync the cmake changes as well:
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 49f96d1..f7076bb 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -225,12 +225,19 @@ if (GGML_CUBLAS)
         # required for dynamic parallelism
         # set(CMAKE_CUDA_SEPARABLE_COMPILATION ON)

-        if (GGML_STATIC)
-            set(GGML_EXTRA_LIBS ${GGML_EXTRA_LIBS} CUDA::cudart_static CUDA::cublas_static CUDA::cublasLt_static)
+        if (GGML_EXTRA_LIBS)
+            if (WIN32)
+                # As of 12.3.1 CUDA Tookit for Windows does not offer a static cublas library
+                set(GGML_EXTRA_LIBS ${GGML_EXTRA_LIBS} CUDA::cudart_static CUDA::cublas CUDA::cublasLt)
+            else ()
+                set(GGML_EXTRA_LIBS ${GGML_EXTRA_LIBS} CUDA::cudart_static CUDA::cublas_static CUDA::cublasLt_static)
+            endif()
         else()
             set(GGML_EXTRA_LIBS ${GGML_EXTRA_LIBS} CUDA::cudart CUDA::cublas CUDA::cublasLt)
         endif()

+        set(GGML_EXTRA_LIBS ${GGML_EXTRA_LIBS} CUDA::cuda_driver)
+
         if (CMAKE_BUILD_TYPE MATCHES Debug)
             set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -lineinfo")
         endif()
```

Should I add a commit?

**Comment by ggerganov** [comment]
No need, I still have to fix the PR number parsing and will include the CMakeLists.txt. Probably will do so tomorrow though

**Pull request merged**
